# docs: http://www.appveyor.com/docs/appveyor-yml
# software installed on build machines: http://www.appveyor.com/docs/installed-software

version: 3.1.{build}

clone_depth: 1

os: Visual Studio 2015

branches:
  only:
    - master

# set env var when running in appveyor so that we can distinguish
# from running locally
environment:
  inappveyor: 1

skip_tags: true

build_script:
  - scripts\appveyor-build.bat

test_script:
  - rel\test_util.exe
  - rel64\test_util.exe

artifacts:
  - path: rel\SumatraPDF.exe
  - path: rel\Installer.exe
  - path: rel\SumatraPDF.pdb.lzsa
  - path: rel64\SumatraPDF.exe
  - path: rel64\Installer.exe
  - path: rel64\SumatraPDF.pdb.lzsa

before_deploy:
- cmd: >-
    7z a Installer-32Bit.zip %APPVEYOR_BUILD_FOLDER%\rel\Installer.exe

    appveyor PushArtifact Installer-32Bit.zip

    7z a SumatraPDF-32Bit.zip %APPVEYOR_BUILD_FOLDER%\rel\SumatraPDF.exe

    appveyor PushArtifact SumatraPDF-32Bit.zip

    7z a Installer-64Bit.zip %APPVEYOR_BUILD_FOLDER%\rel64\Installer.exe

    appveyor PushArtifact Installer-64Bit.zip

    7z a SumatraPDF-64Bit.zip %APPVEYOR_BUILD_FOLDER%\rel64\SumatraPDF.exe

    appveyor PushArtifact SumatraPDF-64Bit.zip

deploy:
- provider: GitHub
  release: Nightly build $(appveyor_build_version)
  description: Nightly build.
  auth_token:
    secure: vTGHHL3yUo0fvU4u/P9YbNrllG2JlHJzuQIZTf9Vdq0ZfuM1x4zu3p1FpMOlhnFf
  artifact: Installer-32bit.zip, SumatraPDF-32Bit.zip, Installer-64Bit.zip, SumatraPDF-64Bit.zip
  prerelease: true
